FROM node:16-alpine

RUN apk update \
  && apk add --virtual build-dependencies \
  build-base \
  gcc \
  wget \
  git \
  python2-dev \
  python3-dev \
  sqlite

RUN apk add --no-cache tzdata

ENV TZ=America/Bogota
