version: '3.8'

services:
  aguasoft:
    build: .
    image: kevinpena/aguasoft:20220628-01
    networks:
      - main
    volumes:
      - db:/db
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: kevinpena/nginx:20220628-01
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
  certbot:
    image: kevinpena/certbot-dns-digitalocean:20220628-01
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    volumes:
      - certbot-var-lib:/var/lib/letsencrypt
      - certbot-etc:/etc/letsencrypt
    secrets:
      - digitalocean_credentials

networks:
  main:

volumes:
  db:
  certbot-var-lib:
  certbot-etc:

secrets:
  digitalocean_credentials:
    external: true
