version: '3.8'
services:
  aguasoft:
    build:
      context: .
      target: server
    image: ghcr.io/kebien6020/aguasoft:20251006-01
    networks:
      - main
    volumes:
      - db:/db
  nginx:
    build:
      context: .
      target: client
    image: ghcr.io/kebien6020/nginx:20251006-01
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
  certbot:
    image: ghcr.io/kebien6020/certbot-dns-digitalocean:20251006-01
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    volumes:
      - certbot-var-lib:/var/lib/letsencrypt
      - certbot-etc:/etc/letsencrypt
    secrets:
      - digitalocean_credentials

networks:
  main:

volumes:
  db:
  certbot-var-lib:
  certbot-etc:

secrets:
  digitalocean_credentials:
    external: true
