version: '3.8'

services:
  aguasoft:
    build: .
    image: kevinpena/aguasoft
    networks:
      - main
    volumes:
      - db:/db
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: kevinpena/dockerfile
    networks:
      - main
    ports:
      - 80:80
    volumes:
      - nginx-etc:/etc/nginx
      - certbot-etc:/etc/letsencrypt
  certbot:
    image: kevinpena/certbot
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    networks:
      - main
    volumes:
      - nginx-etc:/etc/nginx
      - certbot-var-lib:/var/lib/letsencrypt
      - certbot-etc:/etc/letsencrypt
    command: run --test-cert -n --nginx -d agua.kevinpena.com --agree-tos --email kevin.pena.prog@gmail.com

networks:
  main:

volumes:
  db:
  nginx-etc:
  certbot-var-lib:
  certbot-etc:
