version: 2.1

orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: cimg/node:13.11
        environment:
          TZ: America/Bogota
    environment:
      TZ: America/Bogota
    steps:
      - run:
          name: Setup timezone
          command: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - checkout
      - node/install-packages
      - run:
          command: |
            echo tz=$TZ
            date
            npm test
workflows:
  node-tests:
    jobs:
      - test
