version: 2.1

orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts
        environment:
          TZ: America/Bogota
    environment:
      TZ: America/Bogota
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
  node-tests:
    jobs:
      - test
